# Site settings
title: Frank Chung
name: Frank Chung

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/ponty33
 - title: LinkedIn
   url: www.linkedin.com/in/frank-chung-952b1b77

#Any buzzword skills you want to include
skills:
 - JavaScript
 - Ruby
 - HTML
 - CSS
 - NodeJS
 - Ajax
 - Express
 - EJS
 - JQuery
 - React
 - SQL
 - MongoDB
 - REST
 - Git


#Work experience is required
roles:
 - title: Assistant Language Teacher
   start: April 2015
   end: March 2018
   employer: Heart Corporation, Yokohama, Japan
   description: 
    <li>Conducted classroom activities with students based on differentiated learning needs</li></br>
    <li>Designed curriculum for weekly classes including written assignments and oral activities</li></br>
    <li>Encouraged students to be confident in speaking English</li></br>
    <li>Assisted Japanese English teachers in classroom activities, lesson plans, instruction</li></br>
 - title: Sales Representative
   start: March 2014
   end: August 2014
   employer: Cellularbaby, B.C., Canada
   description:  
    <li>Educated and engaged customers through product demonstrations</li></br> 
    <li>Handled phone inquiries from customers on billing issues or troubleshooting errors</li></br>
    <li>Educated customers regarding the benefits of products and services</li></br>
    <li>Trained new employees in sales skills, product design specification, and company system</li></br>
 - title: General Service Assistant
   start: September 2013
   end: March 2014
   employer: T&T Supermarket, B.C., Canada
   description: 
    <li>Responded to customer inquiries in a professional manner</li></br>
    <li>Cashier experience, maintaining daily accounting of own till amount</li></br>
    <li>Educated customers regarding the benefits of products and services</li></br>
   
#Education is required
education:
 - level: Web Development Bootcamp
   school: Lighthouse Labs
   date: 2018
   subject: Web Development
 
 - level: Bachelor of Science (B.Sc.)
   school: Simon Fraser University
   date: 2013
   subject: Chemistry and Statistic


#List of interesting Github repo/projects to include - optional
github:
 - ponty33/tweeter
 - ponty33/tinyApp



